# frozen_string_literal: true

source "https://rubygems.org"

# ActiveSupport is a toolkit of support libraries and Ruby core extensions extracted 
# from the Rails framework. Rich support for multibyte strings, internationalization, 
# time zones, and testing.
gem 'activesupport', '~> 7.0', '>= 7.0.4.1'

# bcrypt() is a sophisticated and secure hash algorithm designed by The OpenBSD 
# project for hashing passwords. The bcrypt Ruby gem provides a simple wrapper for 
# safely handling passwords.
gem 'bcrypt', '~> 3.1', '>= 3.1.18'

# Draper adds an object-oriented layer of presentation logic to your Rails apps.
gem 'draper', '~> 4.0', '>= 4.0.2'

# i18n is a gem to provide internationalization support for Ruby.
gem 'i18n', '~> 1.12'

# JSONAPI::Serializers is a simple library for serializing Ruby objects and 
# their relationships into the JSON:API format. 
# This library is up-to-date with the finalized v1 JSON API spec.
gem 'jsonapi-serializers', '~> 1.0', '>= 1.0.1'

# Pg is the Ruby interface to the PostgreSQL RDBMS. 
# It works with PostgreSQL 9.3 and later.
gem 'pg', '~> 1.4', '>= 1.4.5'

# Rake is a Make-like program implemented in Ruby. Tasks and dependencies are 
# specified in standard Ruby syntax.
gem 'rake', '~> 13.0', '>= 13.0.6'

# Sinatra is a DSL for quickly creating web applications in Ruby with minimal 
# effort.
gem 'sinatra', '~> 3.0', '>= 3.0.5'

# Sinatra-Contrib is a collection of useful Sinatra extensions.
gem 'sinatra-contrib', '~> 3.0', '>= 3.0.5'

# Sinatra-ActiveRecord extends Sinatra with ActiveRecord helpers.
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.26'

# Warden is an authentication library compatible with all Rack-based frameworks
gem 'warden', '~> 1.2', '>= 1.2.9'

group :development, :test do
  # Foreman is a process manager for applications with multiple components.
  gem 'foreman', '~> 0.87.2'

  # Puma is a simple, fast, threaded, and highly parallel HTTP 1.1 server for 
  # Ruby/Rack applications. Puma is intended for use in both development and 
  # production environments.
  gem 'puma', '~> 6.0', '>= 6.0.2'
end